### ISSUE TITLE
Outdated prisma documentation

### ISSUE THREAD

**Issue by CSenshi** [getsentry/sentry-docs#12184]
### SDK

All JavaScript SDKs

### Description

Prisma launched new version of 6.1.0 where tracing is not in previewFeature and some additional things need to be done to be able to trace application. Docs need to be updated 

https://github.com/prisma/prisma/releases/tag/6.1.0

**Comment by maksym-boytsov** [comment]
> Came across this issue and [getsentry/sentry-javascript#14793](https://github.com/getsentry/sentry-javascript/issues/14793) due to an attempt at upgrading our Prisma dependencies to 6.2.1 (from 6.0.1). (aside: prisma/instrumentation _seems_ to work with 6.0.1 🤷 )
> 
> Error we encountered for people searching:
> 
> this.getGlobalTracingHelper(...).dispatchEngineSpans is not a function
> For reference, a [similar issue](https://github.com/prisma/prisma/issues/25978) was reported to Prisma for highlight.io, which is being fixed in [this highlight.io PR](https://github.com/highlight/highlight/pull/9744/commits/4dc72e202f757fb180875412a84abb41de8c29e6#diff-f5ed2ccca75a06fb358fddbbfb95937190dd1bf3e151e7f1ca5e57afe5a20212).

We're seeing the same issue after upgrading to 6.1

**Comment by s1gr1d** [comment]
The major version 8 of the SDKs will only support Prisma v5 ([see integration docs](https://docs.sentry.io/platforms/javascript/guides/node/configuration/integrations/prisma/)).

We decided to add support for the new version in v9, which is released soon (soon as in Januaray/Feburary). When it is released, you can upgrade Sentry to get Prisma v6 support.
